import"./assets/modulepreload-polyfill-B5Qt9EMX.js";import{a as c,i as m,S as d}from"./assets/vendor-DkEYWuMb.js";function s(a,l,o,t){l>0&&o>0&&(document.querySelector(".loader").classList.toggle("visually-hidden"),c.get("https://pixabay.com/api/",{params:{key:"49309273-01bbbdbc5dd72a8afdb67bc06",q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,page:l,per_page:o}}).then(r=>{t(r.data.hits)}).catch(r=>{console.log(r)}).finally(()=>{document.querySelector(".loader").classList.toggle("visually-hidden")}))}const e={searchText:"",carrentPage:1,pageLen:20,maxItems:60,direction:"toBottom"};let i;function n(a){p(a),f()}function g(){document.querySelector(".gallery").outerHTML='<ul class="gallery"></ul>'}function p(a){if(a.length<1)m.error({message:"Sorry, there are no images matching your search query. Please try again!",close:!0,timeout:5e3,position:"topRight"});else{const l=document.createDocumentFragment(),o=document.querySelector(".gallery");for(const t of a){const r=document.createElement("li");r.classList.add("gallery-item"),r.innerHTML=`<div class="gallery-div">
        <a class="gallery-link" href="${t.largeImageURL}">
          <img class="gallery-image" src="${t.webformatURL}" alt="${t.tags}">
        </a>
      </div>
      <div class="img-footer">
        <div class="footer-item"><p>Likes</p><p>${t.likes}</p></div>
        <div class="footer-item"><p>Views</p><p>${t.views}</p></div>
        <div class="footer-item"><p>Comments</p><p>${t.comments}</p></div>
        <div class="footer-item"><p>Downloads</p><p>${t.downloads}</p></div>
      </div>`,l.appendChild(r)}if(console.log(`Додавав ${e.direction}`),e.direction==="toBottom"){for(console.log(`To bottom ${l}`),o.appendChild(l),console.log(`Галерея after add = ${o.children.length} елементів`);o.children.length>e.maxItems;)o.removeChild(o.firstElementChild);console.log(`Gallery after del from bottom = ${o.children.length} elements`)}else if(e.direction==="toTop"){const t=o.scrollHeight;o.prepend(l);const r=o.scrollHeight;for(window.scrollBy(0,r-t);o.children.length>e.maxItems;)o.removeChild(o.lastElementChild);console.log(`Gallery after del from bottom = ${o.children.length} elements`)}}}function h(){e.runStarted=!0;const a=new IntersectionObserver((l,o)=>{const t={markerTop:!1,markerBottom:!1};l.forEach(r=>{r.isIntersecting&&(console.log(r.target.classList[1]),r.target.classList[1]==="marker-top"?t.markerTop=!0:r.target.classList[1]==="marker-bottom"&&(t.markerBottom=!0))}),t.markerBottom&&!t.markerTop?(e.direction="toBottom",s(e.searchText,++e.carrentPage,e.pageLen,n)):!t.markerBottom&&t.markerTop&&(e.direction="toTop",e.carrentPage>3&&s(e.searchText,--e.carrentPage-2,e.pageLen,n)),console.log(t),console.log(`Page = ${e.carrentPage} `)});a.observe(document.querySelector([".marker-top"])),a.observe(document.querySelector([".marker-bottom"]))}function f(){i?i.refresh():i=new d(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250,showCounter:!0,disableScroll:!0,navText:["←","→"],closeText:"×"})}h();document.querySelector(".form").addEventListener("submit",function(a){a.preventDefault(),g(),e.searchText=a.target.elements["search-text"].value,e.direction="toBottom",e.carrentPage=1,s(e.searchText,e.carrentPage,e.pageLen,n)});
//# sourceMappingURL=index.js.map
