import{a as c,i as n,S as d}from"./assets/vendor-DkEYWuMb.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&t(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function t(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();function u(o,i,s,t){document.querySelector(".loader").classList.toggle("visually-hidden"),c.get("https://pixabay.com/api/",{params:{key:"49309273-01bbbdbc5dd72a8afdb67bc06",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:i,per_page:s}}).then(e=>{t(e.data.hits)}).catch(e=>{n.error({title:"Помилка!",message:e.message,position:"topRight"})}).finally(()=>{document.querySelector(".loader").classList.toggle("visually-hidden")})}let l;function p(o){f(o),g()}function m(){document.querySelector(".gallery").outerHTML='<ul class="gallery"></ul>'}function f(o){if(o.length<1)n.error({message:"Sorry, there are no images matching your search query. Please try again!",close:!0,timeout:5e3,position:"topRight"});else{const i=document.createDocumentFragment(),s=document.querySelector(".gallery");for(const t of o){const e=document.createElement("li");e.classList.add("gallery-item"),e.innerHTML=`<div class="gallery-div">
        <a class="gallery-link" href="${t.largeImageURL}">
          <img class="gallery-image" src="${t.webformatURL}" alt="${t.tags}">
        </a>
      </div>
      <div class="img-footer">
        <div class="footer-item"><p>Likes</p><p>${t.likes}</p></div>
        <div class="footer-item"><p>Views</p><p>${t.views}</p></div>
        <div class="footer-item"><p>Comments</p><p>${t.comments}</p></div>
        <div class="footer-item"><p>Downloads</p><p>${t.downloads}</p></div>
      </div>`,i.appendChild(e)}s.appendChild(i)}}function g(){l?l.refresh():l=new d(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250,showCounter:!0,disableScroll:!0,navText:["←","→"],closeText:"×"})}document.querySelector(".form").addEventListener("submit",function(o){o.preventDefault(),m(),u(o.target.elements["search-text"].value,1,42,p)});
//# sourceMappingURL=index.js.map
